# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Letsrun' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
source ‘https://github.com/CocoaPods/Specs/git'
  use_frameworks!




  	pod ‘Bond’, ‘4.0.0’
 	pod “ConvenienceKit”
	pod 'Firebase'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'GoogleSignIn'

	pod ‘SwiftHEXColors’

end
